services:
  fracture:
    build: fracture
    restart: unless-stopped
    stop_grace_period: 3s
    privileged: true
    ports:
      - 3000:5000

  haven:
    build: haven
    restart: unless-stopped
    stop_grace_period: 3s
    privileged: true
    ports:
      - 3001:5000

  summit:
    build: summit
    restart: unless-stopped
    stop_grace_period: 3s
    privileged: true
    ports:
      - 3002:5000
